name: Gradle wrapper validator

on:
  pull_request:
    paths:
      - 'gradlew'
      - 'gradlew.bat'
      - 'gradle/wrapper/'
  push:
    branches:
      - main
    paths:
      - 'gradlew'
      - 'gradlew.bat'
      - 'gradle/wrapper/'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
